### ISSUE TITLE
does not parse correctly the idpEntityId for login.id.tim.it

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#12]
[this test](https://github.com/italia/spid-php-lib/blob/feature/unit-tests/tests/SpTest.php#L56) fails:
```
 ✘ Can load all idp metadata
   │
   │ Failed asserting that 'https://login.id.tim.it/affwebservices/public/saml2slo' contains "https://login.id.tim.it/affwebservices/public/saml2sso".
   │ 
   │ /home/paolog/Sviluppo/teamdigitale/italia/spid-php-lib/tests/SpTest.php:58
```
a dump of the retrieved IdP shows:
```
object(Italia\Spid\Spid\Saml\Idp)#68 (7) {
  ["idpFileName"]=>
  string(5) "idp_3"
  ["metadata"]=>
  array(4) {
    ["idpEntityId"]=>
    string(54) "https://login.id.tim.it/affwebservices/public/saml2sso"
    ["idpSSO"]=>
    string(54) "https://login.id.tim.it/affwebservices/public/saml2sso"
    ["idpSLO"]=>
    string(54) "https://login.id.tim.it/affwebservices/public/saml2slo"
    ["idpCertValue"]=>
    string(1428)
...
```

**Comment by alexrj** [comment]
Non so se è collegato, ma qui:

https://github.com/italia/spid-php-lib/blob/b8fb960a39f8febf92fc9ea32df6e637fbbdccb7/src/Spid/Saml.php#L32

viene usato come chiave dell'array interno il path del file. Dovrebbe essere invece l'entityID risultante da parsing, altrimenti come fa poi `getIdp()` a trovarlo?

https://github.com/italia/spid-php-lib/blob/b8fb960a39f8febf92fc9ea32df6e637fbbdccb7/src/Spid/Saml.php#L128-L131

(suggerisco di usare `$entityID` nella signature di `getIdp()` per chiarire cosa si aspetta. Non esiste un concetto di "IdP Name")

**Comment by simevo** [comment]
download the production idp metadata with `bin/download_idp_metadata.php examples/simple/idp_metadata/` add this test case to `tests/SpTest.php` to reproduce:
```
public function testCanLoadAllIdpMetadata(): void
{
    $sp = new Italia\Spid\Sp(SpTest::$settings);
    $idps = ['idp_1', 'idp_2', 'idp_3', 'idp_4', 'idp_5', 'idp_6', 'idp_7', 'idp_8', 'testenv2'];
    foreach ($idps as $idp) {
        $sp->loadIdpFromFile($idp);
        $retrievedIdp = $sp->getIdp($idp);
        $this->assertEquals($retrievedIdp->idpFileName, $idp);
        // var_dump($retrievedIdp);
        $idpEntityId = $retrievedIdp->metadata['idpEntityId'];
        $idpSSO = $retrievedIdp->metadata['idpSSO'];
        $this->assertContains($idpEntityId, $idpSSO);
        $idpSLO = $retrievedIdp->metadata['idpSLO'];
        $this->assertContains($idpEntityId, $idpSLO);
    }
    $settings1 = SpTest::$settings;
    unset($settings1['sp_entityid']);
    $this->expectException(\Exception::class);
    $sp = new Italia\Spid\Sp($settings1);
}
```

**Comment by lorenzocattaneo** [comment]
@simevo  @alexrj fix ora presente su master. Per qualche motivo TIM utilizza l'url del proprio SLO come entityID, quindi il precedente test che assumeva la struttura degli url essere entityID + route SLO/SSO falliva. Ora controlliamo che tutti gli url facciano parte dello stesso dominio per correttezza.
