### ISSUE TITLE
Log delle richieste come da 4.2. TRACCIATURE SERVICE PROVIDER

### ISSUE THREAD

**Issue by deligant** [italia/spid-php-lib#120]
Vorrei sapere se è previsto il log delle tracciature a carico dei SP come da norma in oggetto.
Posso anche iniziare a sviluppare il relativo codice, ma gradirei un contatto per stabilire come procedere ed eventualmente fornire un PR con almeno una rudimentale procedura di log su filesystem.

Grazie mille
Chris

**Comment by lorello** [comment]
@deligant può essere che questo sia lo stesso problema segnalato in #112 ?

**Comment by lussoluca** [comment]
Duplicato di #112
