### ISSUE TITLE
Conformità ad Avviso 29v3

### ISSUE THREAD

**Issue by StefanoPernat** [italia/spid-php-lib#122]
Buongiorno stò implementando un sp, l'avviso 29v3 dichiara l'obbligatorietà del campo   <md:ContactPerson> come 
descritto qui [Avviso29v3](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n29v3-specifiche_sp_pubblici_e_privati_0.pdf)

il saml-checker lo evidenzia come errore

Mi sapete indirizzare su come fare ad includerlo nel metadata generato da spid-php-lib?

Grazie in anticipo

Stefano

**Comment by lorello** [comment]
guarda la #114

**Comment by lussoluca** [comment]
Duplicato di #114
