### ISSUE TITLE
Livelli di autenticazione L1, L2 e L3

### ISSUE THREAD

**Issue by StefanoDevPro** [italia/spid-php-lib#128]
Ciao a tutti, credo di avere un po' di confusione sui livelli di autenticazione. Dalle regole tecniche deduco che ad impostare il livello consentito sono le righe della request, che ho impostato in questa maniera:

<samlp:RequestedAuthnContext Comparison="minimum">
    <saml:AuthnContextClassRef>
        https://www.spid.gov.it/SpidL1
    </saml:AuthnContextClassRef>    
</samlp:RequestedAuthnContext>

consentendo così l'accesso a tutti e tre i livelli.
Il problema è che se imposto la mia request in quest'altra maniera:

<samlp:RequestedAuthnContext Comparison="exact">
    <saml:AuthnContextClassRef>
        https://www.spid.gov.it/SpidL1
    </saml:AuthnContextClassRef>    
</samlp:RequestedAuthnContext>

non dovrebbe consentirmi l'accesso ai livelli diversi da L1, ma questo non accade, se nell'utilizzo di testenv2 e forzo il livello a 3, l'autenticazione avviene comunque. Cosa succede? Come devo rimediare?

Grazie in anticipo

**Comment by umigliore** [comment]
È richiesto da Agid l'impostazione del livello "minimo" (immagino che sia perché i livelli superiori includono anche i livelli inferiori). Puoi leggere nella issue #84 qualche info sull'argomento

**Comment by StefanoDevPro** [comment]
Grazie @umigliore, quindi mi confermi che se imposto la Comparison="minimum" e AuthnContextClassRef a https://www.spid.gov.it/SpidL1, l'accesso è sempre consentito a tutti i livelli, vero?

**Comment by umigliore** [comment]
Si, se il livello minimo di accesso è L1, un utente con i 'maggiori' poteri L2 può sicuramente accedere.
