### ISSUE TITLE
Response corretta

### ISSUE THREAD

**Issue by StefanoDevPro** [italia/spid-php-lib#129]
Buongiorno a tutti, durante l'ultima validazione di SPID mi è stato segnalato un problema sull'invio della response corretta (test 01 di Spid-Saml-Check). In realtà, quando invio la response corretta, vengo dirottato sulla pagina di autenticazione /views/acs.php dove è presente, come prima azione, il metodo "isAuthenticated()" di questa libreria. Come faccio ad avere l'ok (come dovrebbe) da parte del test eseguito se il metodo non mi autentica? Cosa sto sbagliando? Cosa devo controllare?

Grazie in anticipo.

**Comment by StefanoDevPro** [comment]
L'utente con il quale dovrei essere autenticato, ha i seguenti dati: 

Name: SpidValidator
Family name: AgID
SpidCode: AGID-001
FiscalNumber: TINIT-GDASDV00A01H501J
Email: spid.tech@agid.gov.it

Come mai non mi autentica?

**Comment by mirkochip88** [comment]
Ho lo stesso problema. La prima chiamata alla libreria mi cancella la Session, per cui anche l'idp. Al secondo tentativo di login tutto ok. Da come ho letto pare sia un problema della libreria saml. Hai risolto alla fine?

**Comment by lussoluca** [comment]
Questo problema è legato a #147, chiudo questa e continuiamo di la
