### ISSUE TITLE
Fatal error su Response corretta - Test 01

### ISSUE THREAD

**Issue by StefanoDevPro** [italia/spid-php-lib#130]
Buongiorno a tutti, sono riuscito a visualizzare l'errore in merito all'invio della response corretta (test 01), scrivo "sono riuscito" perchè è un errore che non appare costantemente, in ogni caso l'autenticazione è sempre fallita, l'errore è il seguente:

Fatal error: Uncaught Exception: Invalid Issuer attribute, expected http://spid.clio.it:8080 but received 
http://localhost:8080 in /srv/pa6.produzione.clio.it/www/spid/vendor/italia/spid-php-lib/src/Spid/Saml/In/Response.php:47 

Stack trace: 
#0 /srv/pa6.produzione.clio.it/www/spid/vendor/italia/spid-php-lib/src/Spid/Saml/In/BaseResponse.php(98): 
Italia\Spid\Spid\Saml\In\Response->validate(Object(DOMDocument), true) 
#1 /srv/pa6.produzione.clio.it/www/spid/vendor/italia/spid-php-lib/src/Spid/Saml.php(296): 
Italia\Spid\Spid\Saml\In\BaseResponse->validate('-----BEGIN CERT...') 
#2 [internal function]: Italia\Spid\Spid\Saml->isAuthenticated() 
#3 /srv/pa6.produzione.clio.it/www/spid/vendor/italia/spid-php-lib/src/Sp.php(36): call_user_func_array(Array, Array) 
#4 /srv/pa6.produzione.clio.it/www/spid/layout/menu.php(15): Italia\Spid\Sp->__call('isAuthenticated', Array) 
#5 /srv/pa6.produzione.clio.it/www/spid/layout/print_top.php(34): include('/srv/pa6.produz...') 
#6 /srv/pa6.produzione.clio.it/www/spid/views/acs.php(10): include('/ in /srv/pa6.produzione.clio.it/www/spid/vendor/italia/spid-php-lib/src/Spid/Saml/In/Response.php on line 47

Qualcuno potrebbe darmi delle indicazioni sulla risoluzione?

Grazie

**Comment by StefanoDevPro** [comment]
Per quale  motivo si aspetta http://spid.clio.it:8080? Quello che invio è http://localhost:8080?
E' possibile che sia stato configurato non correttamente spid-saml-check?

Nessuna indicazione?

**Comment by lussoluca** [comment]
Esatto, l'entity id del service provider deve combaciare con quello registrato nell'idp.
