### ISSUE TITLE
Fatal error su Logout

### ISSUE THREAD

**Issue by StefanoDevPro** [italia/spid-php-lib#131]
Ciao a tutti, ma sono solo io a riscontrare tutti questi errori? Dopo essermi autenticato, cliccando sul logout ho il segente errore:

Notice: Trying to get property 'nodeValue' of non-object in /srv/pa6.produzione.clio.it/www/spid/vendor/italia/spid-php-lib/src/Spid/Saml/In/LogoutResponse.php on line 37

Fatal error: Uncaught Exception: Invalid Issuer attribute, expected http://spid.clio.it:8080 but received in /srv/pa6.produzione.clio.it/www/spid/vendor/italia/spid-php-lib/src/Spid/Saml/In/LogoutResponse.php:37 Stack trace: #0 /srv/pa6.produzione.clio.it/www/spid/vendor/italia/spid-php-lib/src/Spid/Saml/In/BaseResponse.php(98): Italia\Spid\Spid\Saml\In\LogoutResponse->validate(Object(DOMDocument), false) #1 /srv/pa6.produzione.clio.it/www/spid/vendor/italia/spid-php-lib/src/Spid/Saml.php(296): Italia\Spid\Spid\Saml\In\BaseResponse->validate('-----BEGIN CERT...') #2 [internal function]: Italia\Spid\Spid\Saml->isAuthenticated() #3 /srv/pa6.produzione.clio.it/www/spid/vendor/italia/spid-php-lib/src/Sp.php(36): call_user_func_array(Array, Array) #4 /srv/pa6.produzione.clio.it/www/spid/layout/menu.php(15): Italia\Spid\Sp->__call('isAuthenticated', Array) #5 /srv/pa6.produzione.clio.it/www/spid/layout/print_top.php(34): include('/srv/pa6.produz...') #6 /srv/pa6.produzione.clio.it/www/spid/views/slo.php(6): include('/srv/pa6.p in /srv/pa6.produzione.clio.it/www/spid/vendor/italia/spid-php-lib/src/Spid/Saml/In/LogoutResponse.php on line 37

Come posso risolverlo?

**Comment by StefanoDevPro** [comment]
Nessuno ha indicazioni sulla risoluzione del problema segnalato?

**Comment by lussoluca** [comment]
Sembra che sia sbagliato il valore dell'Issuer, che deve combaciare tra sp e idp
