### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by abackenddev** [italia/spid-php-lib#135]
Good evening,
I would like to ask why the library is not compatible with php 8 and later and if any upgrade has been planned.
Thank you

**Comment by lussoluca** [comment]
We're working on the new release that will be compatibile with php8

**Comment by francescodiperna** [comment]
Salve, la libreria è compatibile con PHP 8.1?

**Comment by lussoluca** [comment]
> Salve, la libreria è compatibile con PHP 8.1?

Si, è compatibile

**Comment by francescodiperna** [comment]
Grazie per la risposta veloce.
