### ISSUE TITLE
Missing attribute in Authnrequest

### ISSUE THREAD

**Issue by manzolo** [italia/spid-php-lib#16]
- Add the ForceAuthn = "true" attribute in case of Spidlevel > 1
- Add the ProtocolBinding attribute = "urn: oasis: names: tc: SAML: 2.0: bindings: HTTP-POST" in all authnrequests

https://github.com/italia/spid-php-lib/blob/master/src/Spid/Saml/Out/AuthnRequest.php

**Comment by lorenzocattaneo** [comment]
Ho aggiunto un fix su master, ora compare l'attributo ForceAuthn. 
Come discusso nella PR, ProtocolBinding non è necessario se si utilizza AssertionConsumerServiceIndex e non è stato aggiunto.
