### ISSUE TITLE
login function parameter ordering

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#20]
`$redirectTo` dovrebbe essere l'ultimo parametro di `login` perchè è "più opzionale" di `$level`

https://github.com/italia/spid-php-lib/blob/master/src/Spid/Interfaces/SpInterface.php#L46

**Comment by lorenzocattaneo** [comment]
Ho pushato un fix su mater. Il parametro è un penultima posizione perchè è stato aggiunto un nuovo parametro $shouldRedirect. Comunque $level è ora antecedente a $redirectTo
