### ISSUE TITLE
turn on travis-ci.com integration

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#23]
dopo la PR #21 è tempo di attivare l'integrazione con travis-ci.com sul repo italia

va poi anche aggiornata la travis build image nel README che punta ancora a https://travis-ci.com/simevo/spid-php-lib, una volta attivata l'integrazione dovrebbe puntare a https://travis-ci.com/italia/spid-php-lib

**Comment by alexrj** [comment]
Attivato: https://travis-ci.org/italia/spid-php-lib
