### ISSUE TITLE
obscure error while displaying metadata when sp.key can not be read

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#27]
# I wish

to have user-friendly error reporting when I commit mistakes while configuring spid-php-lib

this really helps in making it easier for people to work with this package

for the metadata route, it should catch exceptions and in case one is fired:
- return a 400 error http code
- set content-type set to `text/html` rather than `text/xml` to avoid browsers trying to render that as XML
- print an explicative error message in the `<body>`

this probably applies to all routes !

# Instead

while following the [docker-compose](https://github.com/italia/spid-php-lib#using-docker-compose) guide to install the demo, I have mistakely set wrong permissions on the file `sp.key`:
```
# ls -l sp.*
-rw-r--r-- 1 1000 1000 1273 Sep  7 10:18 sp.crt
-rw-r----- 1 1000 1000 1704 Sep  7 10:18 sp.key
```

if one knows the root cause, the problem is easy to fix with:
```
cd example
chmod o+r sp.key
```

but if I go to http://localhost:8099/metadata I get this in chromium:
```
This page contains the following errors:
error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.
````
![image](https://user-images.githubusercontent.com/8254819/45214557-1104c380-b29b-11e8-8d03-5d2204debade.png)
or in Firefox:
```
Errore interpretazione XML: contenuto illegale dopo l’elemento
Indirizzo: http://localhost:8099/metadata
Riga numero 2, colonna 1:<b>Fatal error</b>:  Uncaught Exception: Failure Signing Data:  - SHA256 in /app/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php:500
^
```
![image](https://user-images.githubusercontent.com/8254819/45215229-1d8a1b80-b29d-11e8-80f6-7c8e8772a4e0.png)

view -> source shows:
```

  | <br />
-- | --
  | <b>Fatal error</b>:  Uncaught Exception: Failure Signing Data:  - SHA256 in /app/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php:500
  | Stack trace:
  | #0 /app/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php(580): RobRichards\XMLSecLibs\XMLSecurityKey-&gt;signOpenSSL('&lt;ds:SignedInfo ...')
  | #1 /app/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php(812): RobRichards\XMLSecLibs\XMLSecurityKey-&gt;signData('&lt;ds:SignedInfo ...')
  | #2 /app/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php(836): RobRichards\XMLSecLibs\XMLSecurityDSig-&gt;signData(Object(RobRichards\XMLSecLibs\XMLSecurityKey), '&lt;ds:SignedInfo ...')
  | #3 /app/src/Spid/Saml.php(113): RobRichards\XMLSecLibs\XMLSecurityDSig-&gt;sign(Object(RobRichards\XMLSecLibs\XMLSecurityKey))
  | #4 [internal function]: Italia\Spid\Spid\Saml-&gt;getSPMetadata()
  | #5 /app/src/Sp.php(29): call_user_func_array(Array, Array)
  | #6 /app/example/views/metadata.php(4): Italia\Spid\Sp-&gt;__call('getSPMetadata', Array)
  | #7 /app/example/index.php(41): require('/app/example/vi...')
  | #8 {main}
  | thrown in <b>/app/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php</b> on line <b>500</b><br />
  |  
```
these messages make it difficult to guess what is the root issue

**Comment by lorenzocattaneo** [comment]
The function does not set the content type, but simply returns a string. In this case, since the string is normally printed as XML content in the view, we return a custom error XML rather than throwing an exception because it would not be shown in XML content type.
