### ISSUE TITLE
authnrequest validation error

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#29]
after [a recent change in testenv2](https://github.com/italia/spid-testenv2/issues/158) spid-php-lib fails to login due to validation error:
```
Elemento | Dettagli errore
-- | --
xpath: {urn:oasis:names:tc:SAML:2.0:protocol}AuthnRequest - attribute: Destination | https://idp.simevo.com/sso è diverso dal valore di riferimento https://idp.simevo.com
```
![image](https://user-images.githubusercontent.com/8254819/45429148-fa97a700-b6a2-11e8-9132-20a5dae4cd13.png)

**Comment by simevo** [comment]
see how this has been fixed in spid-perl:
https://github.com/italia/spid-perl/commit/2ef2564d38c21f49eec50c30b13d93ddf93a1443

**Comment by lorenzocattaneo** [comment]
fix ora su master
