### ISSUE TITLE
examples dir rearrangent: failing CI and README update

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#30]
il travis-ci fallisce perchè si sono spostate le directories example -> examples/simple

inoltre bisogna aggiornare il README e facendo ciò ritestare sia l'esempio simple che quello docker-compose

**Comment by lorenzocattaneo** [comment]
update: directory travis corretta, i test sembrano fallire solo con PHP 7.0. Gli stessi test lanciati manualmente in locale con la stessa versione vanno a buon fine. 
Da una prima analisi sembra un problema con lo script di download dei metadati IDP.

**Comment by simevo** [comment]
l'errore su Travis con PHP 7.0 è perché https://loginspid.aruba.it/metadata è incompatibile con la versione di SSL compilata dentro il PHP 7.0 nell'immagine Travis, vedi: https://stackoverflow.com/questions/38375211/curl-error-35-gnutls-handshake-failed/38429611

con la PR #35 il travis passa, perché vede che c'è stato l'errore e salta l'idp 5 (aruba)
