### ISSUE TITLE
elencare nel README esempi / librerie / plugin / bundles che usano questa libreria

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#37]
al momento:
- https://github.com/simevo/spid-php-lib-example
- https://github.com/italia/spid-symfony-bundle
- https://github.com/simevo/spid-symfony3-example
- https://github.com/simevo/spid-wordpress

a breve:
- https://github.com/simevo/spid-laravel
...

**Comment by lorenzocattaneo** [comment]
fixed with pull request #52
