### ISSUE TITLE
implement AuthnRequest HTTP-POST binding

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#4]
must extract the XML signing code borrowed from onelogin/php-saml/src/Saml2/Utils.php and onelogin/php-saml/src/Saml2/Metadata.php found here:
https://github.com/simevo/spid-php3/blob/master/src/Spid/Saml.php#L92-L123
and move it to a helper class

**Comment by lorenzocattaneo** [comment]
both authn e logout post binding requests now on master
