### ISSUE TITLE
verifica delle firme delle Assertions se presenti

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#40]
regole tecniche paragrafo 1.3.1. "REGOLE DI PROCESSAMENTO DELLA `<RESPONSE>`":

> Alla ricezione `<response>` qualunque sia il binding utilizzato il Service Provider prima di utilizzare l’asserzione deve operare almeno le seguenti verifiche: ... controllo delle firme presenti nella `<Assertion>` e nella `<response>`

**Comment by lorenzocattaneo** [comment]
Funzionalità già presente in metodo validate() in BaseResponse

**Comment by simevo** [comment]
OK allora metti la spunta nel README in corispondenza della #40 (questa)
