### ISSUE TITLE
GetBindingLocation in Base class is not returning Identity provider's complete URL

### ISSUE THREAD

**Issue by giuliogatto** [italia/spid-php-lib#50]
I am trying the Docker-compose example from:
https://github.com/simevo/spid-wordpress/tree/master/docker
but I find an issue when clicking the 'Accedi con SPID usando testenv2 come IdP' button.
The issue is that the application is redirecting me to the wrong URL (http://localhost:8099/sso?SAMLRequest=xxx which is the Service Provider url) instead of http://localhost:8088/sso?SAMLRequest=xxx which is the Identity Provider url).
The result is a NOT FOUND error.

After a bit of investigation the problem seems to be in the method GetBindingLocation of Base class:
https://github.com/italia/spid-php-lib/blob/ac609f350c0e09d936a8f139492108eb443fb625/src/Spid/Saml/Out/Base.php#L67

which seems to skip the Identity Provider url when building the redirect, infact if I change that line to:

`if ($binding == $val['binding']) $location = $this->idp->metadata["idpEntityId"].$val['location'];`

everything works.

BTW: I am not sure if that's the right place to compose the complete url (maybe it should be inside the IDP class itself).

**Comment by lorenzocattaneo** [comment]
see [https://github.com/italia/spid-testenv2/issues/193](https://github.com/italia/spid-testenv2/issues/193)

I'll be adding some extra checks on our end to better signal the error, but as a temporary solution you could manually edit the IDP metadata you downloaded.

**Comment by simevo** [comment]
if the testenv does not comply to our request, we can probably handle it with something like:
```
if ($binding == $val['binding']) {
    if ($val['location'][0] == '/') {
        // relative url
        $location = $this->idp->metadata["idpEntityId"].$val['location'];
    } else {
        // absolute url
        $location = $val['location'];
    }
}
```

**Comment by simevo** [comment]
PR https://github.com/italia/spid-testenv2/pull/194 was merged so the problem should be gone 

waiting for confirmation ...

**Comment by simevo** [comment]
solved; if you are using docker, remember to `docker pull italia/spid-testenv2`
