### ISSUE TITLE
do not ship any IdP metadata with example

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#55]
[this dir](https://github.com/italia/spid-php-lib/tree/master/example/idp_metadata) should only contain `put_idp_metadata_here`

**Comment by lorenzocattaneo** [comment]
fixed with [https://github.com/italia/spid-php-lib/commit/c676d040cfed02559610e983f9f0b0e4d31a1bd9](https://github.com/italia/spid-php-lib/commit/c676d040cfed02559610e983f9f0b0e4d31a1bd9)
