### ISSUE TITLE
spid-smart-button example: enable production IdPs if their metadata is available

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#56]
I downloaded the metadata for all production IdPs with `bin/download_idp_metadata.php example/idp_metadata/`, but when I run the spid-smart-button integration example, only testenv2 is enabled:
![image](https://user-images.githubusercontent.com/8254819/46569238-3c3e0980-c952-11e8-9f93-5ef6a44b9c3d.png)
I tried this patch but for some reason it does not work:
```
@@ -39,7 +39,11 @@ $mapping = $sp->getIdpList();
         },
         // At least one supported IDP must be provided
         supported: [
-            "<?php echo $mapping['testenv'] ?>"
+            <?php
+            foreach ($mapping as $key => $value) {
+                echo "'" . $value . "',";
+            }
+            ?>
```

**Comment by lorenzocattaneo** [comment]
fixed in [this commit](https://github.com/italia/spid-php-lib/commit/c676d040cfed02559610e983f9f0b0e4d31a1bd9#diff-859f909d78aea99c2738a519c9b745a7)
