### ISSUE TITLE
validate attribute names

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#58]
valid attribute names according to: https://www.agid.gov.it/sites/default/files/repository_files/regole_tecniche/tabella_attributi_idp_v1_0.pdf

attributi identificativi:
- gender
- companyName
- registeredOffice
- fiscalNumber
- ivaCode
- idCard
- spidCode
- name
- familyName
- placeOfBirth
- countyOfBirth
- dateOfBirth

attributi secondari:
- mobilePhone
- email
- address
- expirationDate
- digitalAddress

**Comment by lorenzocattaneo** [comment]
fixed in [v0.20](https://github.com/italia/spid-php-lib/releases/tag/v0.20)
