### ISSUE TITLE
Error Assertion must be Signed

### ISSUE THREAD

**Issue by ghost** [italia/spid-php-lib#77]
Hello,
I implemented spid lip php with spid smart button. I'm testing the implementation on idp.gov.it. Therefore the login happens regularly, but in the redirect to the sp I always receive the following error:

Uncaught Exception: Invalid Response. Assertion must be signed in /web/htdocs/www.econverter.it/home/src/Spid/Saml/In/BaseResponse.php:92
I still receive the xml response with all the attributes of the authenticated user.

Can you help me? What can this error be due to?

I am attaching the XML fragment of the assertion

Thanks

![assertion](https://user-images.githubusercontent.com/23119024/59379625-6785bd80-8d57-11e9-9162-023ef58b059c.png)

**Comment by simevo** [comment]
first you should try the local test environment [spid-testenv2](https://github.com/italia/spid-testenv2); does your SP work against the local test environment ?
the [troubleshooting tips](https://github.com/italia/spid-php-lib#troubleshooting) could help clarify what is going on

**Comment by simevo** [comment]
can we close this issue ?

**Comment by lussoluca** [comment]
I'm closing this for lack of response. Feel free to reopen.
