### ISSUE TITLE
publish on packagist

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#8]

**Comment by simevo** [comment]
nell'attesa questo pacchetto si può già installare con composer così: https://github.com/simevo/spid-wordpress/blob/master/composer.json#L15

**Comment by simevo** [comment]
ciao @pdavide tempo fa mi dicevi che sei il proprietario dell'[account italia su packagist](https://packagist.org/packages/italia/), penso che siamo pronti per pubblicare questa lib su packagist !

**Comment by pdavide** [comment]
Ciao @simevo ho provveduto a pubblicare la lib su packagist.
Se mi dai il tuo username di packagist ti aggiungo come mantainer.

https://packagist.org/packages/italia/spid-php-lib
