### ISSUE TITLE
Attributo "Comparison" di RequestedAuthnContext nell'AuthRequest

### ISSUE THREAD

**Issue by umigliore** [italia/spid-php-lib#84]
Nel responso di Agid alla nostra richiesta di validazione hanno risposto che "gli SP possono solo effettuare request con livelli SPID "minimi".

Mi sembra che l'attributo "Comparison" di RequestedAuthnContext nell'AuthRequest sia fissato nel codice come "exact" nella riga 36 del file 
spid-php-lib/src/Spid/Saml/Out/AuthnRequest.php:

```
<samlp:RequestedAuthnContext Comparison="minimum">
   <saml:AuthnContextClassRef>https://www.spid.gov.it/SpidL$level</saml:AuthnContextClassRef>
</samlp:RequestedAuthnContext>
```
È possibile modificarlo in runtime senza modificare la libreria?

**Comment by simevo** [comment]
Ciao ! ho aggiunto nei `$settings` un'opzione `sp_comparison` facoltativa per cambiare la `Comparison` di `RequestedAuthnContext` nell'`AuthRequest`, ma per ora non è rilasciata come versione ufficiale della libreria.

Se puoi prova a testare questa versione:
https://github.com/italia/spid-php-lib/tree/feature/issue-84-comparison

P.S. sarei anche curioso di sapere se agli IDP piace la `Comparison` in caratteri maiuscoli es. `MINIMUM`

**Comment by umigliore** [comment]
Grazie, per fare la prova devo aggiungere un po' di controlli della Request. Ho visto che c'è una pull request in attesa che risolverebbe buona parte dei problemi, tu sai perché non è stata ancora accettata?

**Comment by simevo** [comment]
Quale ? la #86 l'ho fatta io ed è basata sul branch `paolog/psr` da cui mi sono staccato per creare la fix che riguarda questa issue (branch `feature/issue-84-comparison`). Le release ufficiali di solito le fa @lorenzocattaneo quando ha tempo ;-)

**Comment by umigliore** [comment]
La #82 di Luglio scorso aggiunge una serie di verifiche alla validità della Request che sono indicati dall'Agid come Fail nella mia richiesta di test: provandoli con il saml-checker sembrano intercettare bene gli errori (test ancora in corso).

**Comment by umigliore** [comment]
I'm testing you changes: it need update the forceAuthn flag to true, if you use "minimum"

I add this row of code:
            if ($comparison == "minimum") {  $force = "true"; }

**Comment by simevo** [comment]
Status update: I plan to create a PR from the branch `feature/issue-84-comparison` as soon as the question in #94 is cleared. All the PRs you see will be then merged, the result tested with [spid-saml-check](https://github.com/italia/spid-saml-check) and released as `spid-php-lib` v0.35.

**Comment by ctrlaltca** [comment]
Buonasera,
  utilizzo la libreria spid-php-lib in un progetto; ho appena ricevuto un responso di Agid relativo al fallimento della nostra validazione. Parte dei problemi risultato già essere stati risolti dalla PR #92, ma sono presenti inoltre due fallimenti relativi a questa issue:
* 95 Assertion - Elemento AuthContextClassRef impostato su https://www.spid.gov.it/SpidL2
* 96 Assertion - Elemento AuthContextClassRef impostato su https://www.spid.gov.it/SpidL3

Il messaggio di fallimento è il seguente:

```
Il test fallisce perché la request è per L1 "exact". In realtà l'utente deve poter accedere sempre con credenziali di livello superiore
```
Impostato nella richiesta `Comparison="minimum"` e ForceAuthn="true", i test vengono superati nel validatore locale.
