### ISSUE TITLE
change default value of accepted_clock_skew_seconds to 300 ?

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#88]
one of the changes introduced by PR #82 was to change the default value of accepted_clock_skew_seconds from 0 to 300 (see https://github.com/italia/spid-php-lib/pull/82/files#diff-4decba2f885c92c26c0cc126383dcafaR21)

it is not clear why we should do that

@i1990jain can you comment ?

**Comment by i1990jain** [comment]
It is the time in seconds skew that is acceptable between client and server when checking OnBefore and NotOnOrAfter. I think it will be better to at least make it to 300 so that in case the user doesn't set it in the config. It will be taken as 300 rather than 0, given the processing time for higher spid levels.

**Comment by simevo** [comment]
Yes, it's also used to validate `IssueInstant`.

The skew is there to allow tolerance for clock misalignment between servers (SP and IdP). The best practices for server admin include running an [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol) daemon which will keep the skew at such low levels (i.e. less than 50 ms) that it's comparable with the network delays.

AFAICT in the SAML ecosystem opinions about what is a reasonable clock skew differ:
- https://github.com/onelogin/ruby-saml#clock-drift (1 s)
- https://github.com/simplesamlphp/simplesamlphp/blob/master/config-templates/config.php#L213 (180 s) 

My opinion is that the defaults we provide should steer library users (SP implementers) towards working in accordance with the best practices. If we provide as default a non-zero skew, we're relaxing security by default. So I believe the default skew should be zero. Users can increase it if they wish, but it's their responsibility.

**Comment by i1990jain** [comment]
I agree with you given the point of view presented regarding implementers who have the possibility to skew it accordingly
