### ISSUE TITLE
base64-encode RelayState in Saml Out Base redirect ?

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#89]
one of the changes introduced by PR #82 was to base64-encode the default value for `RelayState` in `Saml/Out/Base` redirect (see https://github.com/italia/spid-php-lib/pull/82/files#diff-9c401dbcc477a4874265ab56a43cd4c5R36), but it was done incorrectly because it should do that only if `$redirectTo` is not set

looking at the _regole tecniche_ here: https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/trasmissione.html#binding-http-redirect it is clear that `SAMLRequest` must be base64-encoded, but not `RelayState` ! 

@i1990jain and @lorenzocattaneo ?

**Comment by i1990jain** [comment]
As RelayState is another component going along with the SAML request component which is encoded. I added this to the relay state also keeping in mind that when the response from the SP comes back it has the RelayState encoded.
For example in the [Spid-saml-check/spid-validator](https://github.com/italia/spid-saml-check/blob/bfd5aa02051c419f3f6c9af73699f044e00644e1/spid-validator/server/spid-validator.js#L155)

**Comment by simevo** [comment]
The code snippet you linked shows the JavaScript `encodeURIComponent` function being applied to both `samlRequest` and `RelayState`, but then only the former is decoded:
https://github.com/italia/spid-saml-check/blob/bfd5aa02051c419f3f6c9af73699f044e00644e1/spid-validator/server/spid-validator.js#L131
```javascript
let xml = PayloadDecoder.decode(samlRequest);
```
https://github.com/italia/spid-saml-check/blob/bfd5aa02051c419f3f6c9af73699f044e00644e1/spid-validator/server/lib/saml-utils.js#L138
```javascript
class PayloadDecoder { static decode(payload) { return samlProtocol.decodeXMLPayload(payload); } }
```
https://github.com/italia/spid-saml-check/blob/bfd5aa02051c419f3f6c9af73699f044e00644e1/spid-validator/server/lib/saml-protocol/protocol-bindings.js#L254
```
// Decodes an SAML payload, which will be base64ed and potentially deflated
function decodeXMLPayload(rawPayload) {
```

The [JavaScript `encodeURIComponent` function](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
) "_encodes a Uniform Resource Identifier (URI) component by replacing each instance of certain characters by one, two, three, or four escape sequences representing the UTF-8 encoding of the character (will only be four escape sequences for characters composed of two "surrogate" characters)_" and is not related to base64-encoding.

Finally looking at `saml-bindings-2.0-os.pdf` from http://docs.oasis-open.org/security/saml/v2.0/

line 226:
> Some bindings define a "RelayState" mechanism for preserving and conveying state information. When such a mechanism is used in conveying a request message as the initial step of a SAML protocol, it places requirements on the selection and use of the binding subsequently used to convey the response. Namely, if a SAML request message is accompanied by RelayState data, then the SAML responder MUST return its SAML protocol response using a binding that also supports a RelayState mechanism, and it MUST place the exact RelayState data it received with the request into the corresponding RelayState parameter in the response.

line 775:
> **RelayState** data MAY be included with a SAML protocol message transmitted with this binding. The value MUST NOT exceed 80 bytes ...

line 789:
> Messages are encoded for use with this binding by encoding the XML into an HTML form control and are transmitted using the HTTP POST method. A SAML protocol message is form-encoded by applying the **base-64 encoding rules to the XML representation of the message** and placing the result in a hidden form control within a form as defined by [HTML401] Section 17. The HTML document MUST adhere to the XHTML specification, [XHTML]. The base64-encoded value MAY be line-wrapped at a reasonable length in accordance with common practice. If the message is a SAML request, then the form control MUST be named **SAMLRequest**. If the message is a SAML response, then the form control MUST be named **SAMLResponse**. 

line 799:
> If a “**RelayState**” value is to accompany the SAML protocol message, it MUST be placed in an additional hidden form control named RelayState within the same form with the SAML message.

It's mentioning base-64 encoding only for the SAML protocol messages in XML format `SAMLRequest` / `SAMLResponse` and not for `RelayState` which is an application-specific token used to identify state. `RelayState` could be an uuid, url, file path or a binary base64-encoded mini-blob for what matters (but then it would be the application's responsibility to encode and decode it, not ours !).
