### ISSUE TITLE
if AuthnRequest RequestedAuthnContext Comparison is set to minimum,  ForceAuthn must be set to true ?

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#94]
see this comment: https://github.com/italia/spid-php-lib/issues/84#issuecomment-567087289

@umigliore can you provide a normative reference for this ? thanks !

**Comment by simevo** [comment]
if the answer is yes, we can implement it as in here: https://github.com/italia/spid-php-lib/pull/87/commits/fc61f0e0b5004e1e472d7037d29369aca2c50de2#diff-d701c062084416d9da7c836d589226e5R24
or with:
```php
if (isset($this->idp->sp->settings['sp_comparison'])) {
    $comparison = $this->idp->sp->settings['sp_comparison'];
} else {
    $comparison = "exact";
}
$force = ($level > 1 || $comparison == "minimum") ? "true" : "false";
```

**Comment by umigliore** [comment]
cfr https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html#authnrequest

The comparison attribute should be minimum because of this note in the doc:
> "N.B. L’Identity Provider ha facoltà di utilizzare per l’autenticazione un livello SPID più alto rispetto a quelli risultanti dall’indicazione del richiedente mediante l’attributo Comparison. Tale scelta non deve comportare un esito negativo della richiesta."

If the Level can be greater than 1, the request should present the flag ForceAuthn:
> The ForceAuthn flag is required if the level could be grater than 1.

**Comment by simevo** [comment]
looking at `saml-core-2.0-os.pdf` from http://docs.oasis-open.org/security/saml/v2.0/

line 1804:
> The `<RequestedAuthnContext>` element specifies the authentication context requirements of
authentication statements returned in response to a request or query. Its RequestedAuthnContextType
complex type defines the following elements and attributes: `<saml:AuthnContextClassRef>` or `<saml:AuthnContextDeclRef>` [One or More]

for SPID, it can be: https://www.spid.gov.it/SpidL1, https://www.spid.gov.it/SpidL2 or https://www.spid.gov.it/SpidL3

line 1812:
> **Comparison** [Optional] Specifies the comparison method used to evaluate the requested context classes or statements, one of "exact", "minimum", "maximum", or "better". The default is "exact". Either a set of class references or a set of declaration references can be used. The set of supplied
references MUST be evaluated as an ordered set, where the first element is the most preferred
authentication context class or declaration. If none of the specified classes or declarations can be satisfied in accordance with the rules below, then the responder MUST return a <Response> message with a second-level <StatusCode> of urn:oasis:names:tc:SAML:2.0:status:NoAuthnContext.
> If Comparison is set to "**exact**" or omitted, then the resulting authentication context in the authentication statement MUST be the exact match of at least one of the authentication contexts specified.
> If Comparison is set to "**minimum**", then the resulting authentication context in the authentication
statement MUST be at least as strong (as deemed by the responder) as one of the authentication
contexts specified.
> If Comparison is set to "**better**", then the resulting authentication context in the authentication
statement MUST be stronger (as deemed by the responder) than any one of the authentication contexts specified.
> If Comparison is set to "**maximum**", then the resulting authentication context in the authentication
statement MUST be as strong as possible (as deemed by the responder) without exceeding the strength of at least one of the authentication contexts specified.

for SPID, any of the 4 values is possible: exact, minimum, better or maximum

line 2042:
> **ForceAuthn** [Optional] A Boolean value. If "true", the identity provider MUST authenticate the presenter directly rather than rely on a previous security context. If a value is not provided, the default is "false". However, if both ForceAuthn and IsPassive are "true", the identity provider MUST NOT freshly authenticate the presenter unless the constraints of IsPassive can be met.

for SPID, ForceAuthn must be true for SpidL2 and SpidL3

sooo, if I request SpidL1 with comparison = minimum, I think ForceAuthn can be false

**Comment by umigliore** [comment]
In the Spid Saml Check tool, it waits in test AuthnRequest for flag set to true.
It says:

>      # ForceAuthn must be true if 'Comparison' is 'minimum' and SPID level is L1

 
https://github.com/italia/spid-saml-check/blob/ed5962b085b6bf2e46367dc7c4b8f5d8623f2272/specs-compliance-tests/test/sp/authn_request_extra.py

**Comment by simevo** [comment]
Ok let's check why is that https://github.com/italia/spid-saml-check/issues/50

**Comment by ctrlaltca** [comment]
A quanto descritto in https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html#authnrequest :

* è obbligatorio`l’attributo ForceAuthn nel caso in cui si richieda livelli di autenticazione superiori a SpidL1 (SpidL2 o SpidL3)`
 * `L’elemento <RequestedAuthnContext> prevede un attributo Comparison con il quale indicare il metodo per stabilire il rispetto del vincolo sul contesto di abilitazione: i valori ammessi per questo attributo sono: exact, minimum, better, maximum`
 * `N.B. L’Identity Provider ha facoltà di utilizzare per l’autenticazione un livello SPID più alto rispetto a quelli risultanti dall’indicazione del richiedente mediante l’attributo Comparison. Tale scelta non deve comportare un esito negativo della richiesta.`

Quindi anche impostando nella richiesta un livello minimo `SpidL1`, l'Idp può autenticare utilizzando un livello SpidL2 o SpidL3, per i quali è obbligatorio prevedere l’attributo `ForceAuthn=true`.

La necessità di questo attributo è stato notato inizialmente indicato come problema nel test-environment ufficiale qui: https://github.com/italia/spid-testenv/issues/37
Lo stesso giorno è stato aggiunto un test specifico per controllare questa condizione nel validatore ufficiale: https://github.com/italia/spid-saml-check/commit/b9d3183e5d835a8f0ce23c8d69ed62cc9610899c

Non ho trovato un'indicazione precisa nella normativa di questo obbligo, se non uno desumibile dalle condizioni qui esposte.

**Comment by simevo** [comment]
Grazie per tutti i commenti, ora mi sono convinto anche io che anche mancando un'indicazione normativa deve essere così se no `Comparison` di fatto diventa `exact` dal momento che l'IdP con `ForceAuthn=false` potrebbe restituire solo SPID L1. La fix sarà inclusa nella nuova release !
