### ISSUE TITLE
report back some details if the AuthnRequest StatusCode is not Success

### ISSUE THREAD

**Issue by simevo** [italia/spid-php-lib#95]
something like: https://github.com/italia/spid-php-lib/pull/87/commits/fc61f0e0b5004e1e472d7037d29369aca2c50de2#diff-4decba2f885c92c26c0cc126383dcafaR152

**Comment by simevo** [comment]
@umigliore can you review how I propose to implement this is the commit 633daa6 ?

**Comment by umigliore** [comment]
It should be ok, because StatusMessage should be used only with StatusCode != success.
